### PR TITLE
Add trafaret date and datetime support

### PR DESCRIPTION
**Pull request by sonerayberk**
Add Trafaret `datetime.date` and `datetime.datetime` support.

### CODE REVIEW

**Comment by Deepwalker** [comment]
We have some existing date related contrib module https://github.com/Deepwalker/trafaret/blob/master/trafaret/contrib/rfc_3339.py
Not sure how to resolve competition – what is your opinion?

**Comment by sonerayberk** [comment]
@Deepwalker Thanks for the feedback!

Here are some pros of the proposal:
- Format support;
- More specific errors;
- Zero Python packages dependency (no `dateutil` requirement);
- Not so primitive data type, but potentially a good idea to have in `base.py` as specialized Python's data type;
- Instant support of `Date` & `DateTime` trafarets via `pip install trafaret`, no `pip install trafaret[rfc3339]` is required.

Your thoughts?

**Comment by sonerayberk** [comment]
@Deepwalker Any updates about the PR?

**Comment by Deepwalker** [comment]
I like this idea Main pros is stdlib only. But I have `version2` branch, and will need to update this implementation to include codes etc as well. So I think what to do first, merge PR or release version2.

**Comment by sonerayberk** [comment]
I can make PR into the `version2` branch as well, no problems

**Comment by sonerayberk** [comment]
@Deepwalker Created PR to `version2` https://github.com/Deepwalker/trafaret/pull/58. 
Will we merge current PR into `master` or should I close it?

**Comment by Arfey** [comment]
close

**Pull request closed without merging**
